name: documenso-production

services:
  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: documenso
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documenso
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documenso"]
      interval: 10s
      retries: 5

  documenso:
    image: documenso/documenso:latest
    depends_on:
      database:
        condition: service_healthy
    environment:
      NEXTAUTH_SECRET: secret
      NEXT_PRIVATE_ENCRYPTION_KEY: CAFEBABE
      NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: DEADBEEF
      NEXT_PRIVATE_DATABASE_URL: postgres://documenso:password@database:5432/documenso
      NEXT_PRIVATE_DIRECT_DATABASE_URL: postgres://documenso:password@database:5432/documenso
      NEXT_PUBLIC_UPLOAD_TRANSPORT: database

      # SMTP settings for free test server
      NEXT_PRIVATE_SMTP_TRANSPORT: smtp-auth
      NEXT_PRIVATE_SMTP_HOST: smtp.freesmtpservers.com
      NEXT_PRIVATE_SMTP_PORT: 25
      NEXT_PRIVATE_SMTP_USERNAME: ""
      NEXT_PRIVATE_SMTP_PASSWORD: ""
      NEXT_PRIVATE_SMTP_FROM_NAME: "No Reply @ Documenso"
      NEXT_PRIVATE_SMTP_FROM_ADDRESS: noreply@documenso.com

      # Signing certificate
      NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH: /app/certs/cert.p12
      NEXT_PRIVATE_SIGNING_PASSPHRASE: password

      # Enable password login + registration without email verification
      NEXT_PUBLIC_ENABLE_PASSWORD_LOGIN: true
      NEXT_PUBLIC_ENABLE_REGISTRATION: true
      NEXT_PUBLIC_ENABLE_UNVERIFIED_EMAILS: true
    ports:
      - "3000:3000"
    volumes:
      - ../../certs:/app/certs


volumes:
  db-data:
